config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("msp", include("microsoft_student_partners.msp.urls", namespace="msp")),
    path("", TemplateView.as_view(template_name="index.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("microsoft_student_partners.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        "certificates/",
        include(
            "microsoft_student_partners.certificates.urls", namespace="certificates"
        ),
    ),
    path(
        "mspsoc/",
        include("microsoft_student_partners.mspsoc.urls", namespace="mspsoc"),
    ),
    path(
        "qpower/",
        include("microsoft_student_partners.qpower.urls", namespace="qpower"),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

microsoft_student_partners/msp/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from microsoft_student_partners.msp.views import MspView

app_name = "msp"
urlpatterns = [
    path("", view=MspView.as_view(), name="home"),
    path(
        "services/",
        TemplateView.as_view(template_name="services.html"),
        name="services",
    ),
    path("about", TemplateView.as_view(template_name="about.html"), name="about",),
    path(
        "contact", TemplateView.as_view(template_name="contact.html"), name="contact",
    ),
]

microsoft_student_partners/mspsoc/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from microsoft_student_partners.mspsoc.views import Mspsoc, Project, Social

app_name = "mspsoc"
urlpatterns = [
    path("", view=Mspsoc.as_view(), name="home"),
    path("project/", view=Project.as_view(), name="project"),
    path(
        "contact/",
        TemplateView.as_view(template_name="mspsoc/contact.html"),
        name="contact",
    ),
    path(
        "schedule/",
        TemplateView.as_view(template_name="mspsoc/schedule.html"),
        name="schedule",
    ),
    path(
        "speakers/",
        TemplateView.as_view(template_name="mspsoc/speakers.html"),
        name="speakers",
    ),
    path(
        "elements/",
        TemplateView.as_view(template_name="mspsoc/elements.html"),
        name="elements",
    ),
    path("social", view=Social.as_view(), name="social"),
]

microsoft_student_partners/users/urls.py
from django.urls import path

from microsoft_student_partners.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

microsoft_student_partners/twitter/models.py
from django.db import models

# Create your models here.

microsoft_student_partners/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

microsoft_student_partners/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

microsoft_student_partners/certificates/views.py
from django.shortcuts import render
from django.views import View

from microsoft_student_partners.certificates.helpers import Certificate


class CertificateView(View):
    template_name = "certificates/project.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        context = {}
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        email = request.POST.get("email")
        event_name = "Sample Event for Testing"  # request.POST.get("event_name")
        print(first_name, last_name, event_name, email)
        img_name = Certificate().certificate(first_name, last_name, event_name, email)
        context["pdf_file"] = img_name + ".pdf"
        context["img_file"] = img_name + ".png"
        return render(request, self.template_name, {"context": context})

microsoft_student_partners/github/views.py
import json

import requests
from django.conf import settings
from django.http import JsonResponse


# Create your views here.


class GitHub:
    def __init__(self):

        self.GITHUB_OAUTH_TOKEN = settings.GITHUB_OAUTH_TOKEN
        self.GITHUB_USERNAME = settings.GITHUB_USERNAME

        self.GH_SESSION = requests.Session()
        self.GH_SESSION.auth = (self.GITHUB_USERNAME, self.GITHUB_OAUTH_TOKEN)

    def get_repository(self, user=None, repo=None):
        REPOS_URL = "https://api.github.com/repos/" + user + "/" + repo
        try:
            repository = json.loads(self.GH_SESSION.get(REPOS_URL).text)
        except:
            repository = {}
        return repository

    def get_language_repo(self, user=None, repo=None):
        LANG_URL = "https://api.github.com/repos/" + user + "/" + repo + "/languages"
        try:
            languages = json.loads(self.GH_SESSION.get(LANG_URL).text)
        except:
            languages = {}
        return languages

microsoft_student_partners/msp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import View

class MspView(View):
    template_name = 'index.html'
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

microsoft_student_partners/mspsoc/views.py
import json

import pandas as pd
from django.conf import settings
from django.shortcuts import render
from django.views import View
import datetime
from microsoft_student_partners.github.views import GitHub
import os.path
import csv
from os import path

from microsoft_student_partners.twitter.views import Twitter

ROOT_DIR = settings.ROOT_DIR
THIS_DIR = str(ROOT_DIR) + "/microsoft_student_partners/mspsoc/"


class Mspsoc(View):
    template_name = "mspsoc/index.html"

    def get(self, request, *args, **kwargs):
        with open("microsoft_student_partners/mspsoc/organizers.json") as json_file:
            organizers = json.load(json_file)
        return render(request, self.template_name, context={"organizers": organizers})


class Project(View):
    template_name = "mspsoc/project.html"

    def get(self, request, *args, **kwargs):
        context = {}
        fetched_info = []
        if os.path.isfile(str(THIS_DIR) + "project.json"):
            with open(
                "microsoft_student_partners/mspsoc/projects_list.json"
            ) as json_file:
                fetched_info = json.load(json_file)
            for info in fetched_info:
                temp_dict = {}
                for key, val in info.items():
                    temp_dict[key] = val
                    context.update(temp_dict)

        gh = GitHub()

        new_fetched_info = []
        with open("microsoft_student_partners/mspsoc/project.json") as json_file:
            project_list = json.load(json_file)["projects"]

        for project in project_list:
            if project["repository"] not in context.keys():
                data = dict()

                repo_details = gh.get_repository(
                    project["username"], project["repository"]
                )
                if repo_details:
                    data[project["repository"]] = repo_details

                data[project["repository"]]["languages"] = {}
                languages = gh.get_language_repo(
                    project["username"], project["repository"]
                )
                if languages:
                    data[project["repository"]]["languages"] = languages

                new_fetched_info.append(data)

                # Writing to sample.json
                context.update(data)
            if new_fetched_info:
                complete_info = fetched_info
                complete_info.extend(new_fetched_info)
                with open(
                    "microsoft_student_partners/mspsoc/projects_list.json", "w"
                ) as projects_list_file:
                    projects_list_file.write(json.dumps(complete_info, indent=4))
        return render(request, self.template_name, {"context": context})


class Social(View):
    template_name = "mspsoc/social.html"

    def get(self, request, *args, **kwargs):
        context = dict()
        twitter_list = []
        twitter = Twitter()
        tweets_hashtags_info = []
        tweets_df = pd.DataFrame()
        CSV_FILE = str(THIS_DIR) + "tweets.csv"
        fetched_info = []
        try:
            if os.path.isfile(str(CSV_FILE)):
                try:
                    tweets_df = pd.read_csv(CSV_FILE)
                except:
                    tweets_df = pd.DataFrame()
        except FileNotFoundError:
            pass
        if not tweets_df.empty or datetime.datetime.now().hour % 2 == 0:
            hashtags = "mspsoc"
            date = "2020-05-05"
            fetched_info = twitter.search_hashtags(hashtags, date)
            with open(str(THIS_DIR) + "tweets.csv", "w") as csv_file:
                csv_writer = csv.writer(csv_file)
                for pair in fetched_info:
                    row = []
                    for key, val in pair.items():
                        row.append(val)
                    csv_writer.writerow(row)
            csv_file.close()
        if not tweets_df.empty or fetched_info:
            print("NO ERROR")
            tweets_df = pd.read_csv(CSV_FILE, delimiter=",")
            print("READ")
            if not tweets_df.empty:
                print("EMPTY")
                for index, row in tweets_df.iterrows():
                    temp = dict()
                    temp["username"] = row[0]
                    temp["name"] = row[1]
                    temp["background_color"] = row[2]
                    temp["image"] = row[3]
                    temp["tweet"] = row[4]
                    twitter_list.append(temp)

        context["twitter"] = twitter_list
        return render(request, self.template_name, {"context": context})

microsoft_student_partners/qpower/views.py
import json

from django.shortcuts import render
from django.views import View


class Qpower(View):
    template_name = "qpower/index.html"

    def get(self, request, *args, **kwargs):
        organizers = dict()
        with open("microsoft_student_partners/qpower/organizers.json") as json_file:
            organizers = json.load(json_file)
        return render(request, self.template_name, context={"organizers": organizers})

microsoft_student_partners/twitter/views.py
from django.shortcuts import render
import json
import tweepy
import requests
from django.conf import settings
import pandas as pd

import csv

# Create your views here.


class Twitter:
    def __init__(self):
        self.TWITTER_CONSUMER_API_KEY = settings.TWITTER_CONSUMER_API_KEY
        self.TWITTER_CONSUMER_SECRET_KEY = settings.TWITTER_CONSUMER_SECRET_KEY
        self.TWITTER_ACCESS_TOKEN = settings.TWITTER_ACCESS_TOKEN
        self.TWITTER_ACCESS_TOKEN_SECRET = settings.TWITTER_ACCESS_TOKEN_SECRET

        auth = tweepy.OAuthHandler(
            self.TWITTER_CONSUMER_API_KEY, self.TWITTER_CONSUMER_SECRET_KEY
        )
        auth.set_access_token(
            self.TWITTER_ACCESS_TOKEN, self.TWITTER_ACCESS_TOKEN_SECRET
        )

        self.TWITTER_API = tweepy.API(auth)

    def get_twitter_user(self, user=None):
        user = self.TWITTER_API.get_user(user)
        return user._json

    def search_hashtags(self, hashtags=None, date=None):
        data = []
        for tweet in tweepy.Cursor(
            self.TWITTER_API.search, q=hashtags, since=date,
        ).items():
            row = {
                "username": tweet.user.screen_name,
                "name": tweet.user.name,
                "background_color": tweet.user.profile_background_color,
                "image": tweet.user.profile_image_url_https.replace(
                    "normal", "400x400"
                ),
                "tweet": tweet.text.encode("utf-8"),
            }
            data.append(row)

        return data

microsoft_student_partners/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

microsoft_student_partners/templates/qpower/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>qpower</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
{#    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicons/favicon.ico' %}">#}
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicons/site.webmanifest' %}">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'mspsoc/css/bootstrap.min.css' %}?{% now 'U' %}">
    <link rel="stylesheet" href="{% static 'mspsoc/css/owl.carousel.min.css' %}?{% now 'U' %}">
    <link rel="stylesheet" href="{% static 'mspsoc/css/magnific-popup.css' %}?{% now 'U' %}">
    <link rel="stylesheet" href="{% static 'mspsoc/css/font-awesome.min.css' %}?{% now 'U' %}">
    <link rel="stylesheet" href="{% static 'mspsoc/css/themify-icons.css' %}?{% now 'U' %}">
    <link rel="stylesheet" href="{% static 'mspsoc/css/nice-select.css' %}?{% now 'U' %}">
    <link rel="stylesheet" href="{% static 'mspsoc/css/flaticon.css' %}?{% now 'U' %}">
    <link rel="stylesheet" href="{% static 'mspsoc/css/animate.css' %}?{% now 'U' %}">
    <link rel="stylesheet" href="{% static 'mspsoc/css/slicknav.css' %}?{% now 'U' %}">
    <link rel="stylesheet" href="{% static 'mspsoc/css/style.css' %}?{% now 'U' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>
    <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->
    {% include 'qpower/header.html' %}

    {% block content %}
    {% endblock content %}

    {% include 'qpower/footer.html' %}
    <!-- JS here -->
    <script src="{% static 'mspsoc/js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{% static 'mspsoc/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'mspsoc/js/popper.min.js' %}"></script>
    <script src="{% static 'mspsoc/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'mspsoc/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'mspsoc/js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'mspsoc/js/ajax-form.js' %}"></script>
    <script src="{% static 'mspsoc/js/waypoints.min.js' %}"></script>
    <script src="{% static 'mspsoc/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'mspsoc/js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'mspsoc/js/scrollIt.js' %}"></script>
    <script src="{% static 'mspsoc/js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'mspsoc/js/wow.min.js' %}"></script>
    <script src="{% static 'mspsoc/js/nice-select.min.js' %}"></script>
    <script src="{% static 'mspsoc/js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'mspsoc/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'mspsoc/js/jquery.countdown.js' %}"></script>
    <script src="{% static 'mspsoc/js/plugins.js' %}"></script>

    <!--contact js-->
    <script src="{% static 'mspsoc/js/contact.js' %}"></script>
    <script src="{% static 'mspsoc/js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'mspsoc/js/jquery.form.js' %}"></script>
    <script src="{% static 'mspsoc/js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'mspsoc/js/mail-script.js' %}"></script>

    <script src="{% static 'mspsoc/js/main.js' %}"></script>

</body>

</html>

microsoft_student_partners/templates/qpower/footer.html
{% load static %}
<!-- footer_start -->
    <footer class="footer footer_bg_1">
        <div class="circle_ball d-none d-lg-block">
            <a href="#top"><img src="https://storage.needpix.com/rsynced_images/arrow-975992_1280.png" alt="" style="max-width: 13%;"></a>
        </div>
            <div class="footer_top">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-4 col-md-4 col-lg-4">
                            <div class="footer_widget">
                                <h3 class="footer_title">
                                  QPower Community
                                </h3>
                                <div class="row">
{#                                  <div class="col-md-4">#}
{#                                    <img src="{% static 'images/QPower-logo.png' %}" style="width: 100%;" class="img-fluid">#}
{#                                  </div>#}
                                  <div class="col-md-12">
                                    <p style="text-align: justify"><img src="{% static 'images/QPower-logo.png' %}" style="width: 30%;float:left;padding: 5px 10px;" class="img-fluid">Q-power is a community of enthusiasts who are willing to learn and contribute towards Quantum Computing
                                    We are scheduling a series from beginners to higher level. Join us.
                                    </p>
                                  </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-4 col-md-4 col-lg-4" style="text-align: center">
                            <div class="footer_widget">
                                <h3 class="footer_title">
                                        Links
                                </h3>
                                <ul>
                                    <li><a href="#top">Home</a></li>
                                    <li><a href="#schedule">Schedule</a></li>
                                    <li><a href="#speakers">Speakers</a></li>
                                    <li><a href="#organizers">Organizers</a></li>
{#                                    <li><a href="{% url 'mspsoc:project' %}">Projects</a></li>#}
                                    <li><a href="{% url 'certificates:home' %}">Certificates</a></li>
                                    <li><a href="#faq">FAQs</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-xl-4 col-md-4 col-lg-4">
                            <div class="footer_widget">
                                <h3 class="footer_title">
                                        <img src="{% static 'microsoft/Visual ID and Logo/Student Partner Visual ID/Blue_White/CMYK/1Line/MSP_visual-ID_CMYK_1line_blue_white.png' %}" alt="" style="width: 100%;">
                                </h3>
                                <p style="text-align: justify">
                                    MSP Global is a community by Microsoft Student Partners to host their events and provide certificates to the participants with the validatiion key and much more.
                                    <br>This is an open source project, Feel free to contribute.<br>
                                    <div class="social_icon">
                                      <a target="_blank" href="https://github.com/ramanaditya/Microsoft-Student-Partners" style="font-size: 1.5em;"><i class="fa fa-github" ></i> <span style="color: white">GitHub</span> </a>
                                    </div>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copy-right_text">
                <div class="container">
                    <div class="footer_border"></div>
                    <div class="row">
                        <div class="col-xl-12">
                            <p class="copy_right text-center">
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    <!-- footer_end -->

microsoft_student_partners/templates/qpower/header.html
{% load static %}
<!-- header-start -->
<header>
  <div class="header-area ">
      <div id="sticky-header" class="main-header-area ">
          <div class="container-fluid p-0">
              <div class="row align-items-center justify-content-between no-gutters">
                  <div class="col-xl-4 col-lg-4">
                      <div class="logo-img">
                          <a href="{% url 'qpower:home' %}">
                            <h4 style="color: white;text-align: left;padding-top: 0.5em;">MICROSOFT <span style="color: #0078D4">STUDENT PARTNERS</span></h4>
{#                              <img src="{% static 'microsoft/Visual ID and Logo/Student Partner Visual ID/Blue_White/CMYK/1Line/MSP_visual-ID_CMYK_1line_blue_white.png' %}" alt="">#}
                          </a>
                      </div>
                  </div>
                  <div class="col-xl-8 col-lg-8">
                      <div class="main-menu  d-none d-lg-block">
                          <nav>
                              <ul id="navigation">
                                  <li><a href="{% url 'qpower:home' %}">home</a></li>
                                  <li><a href="#schedule">Schedule</a></li>
{#                                  <li><a href="#">blog <i class="ti-angle-down"></i></a>#}
{#                                      <ul class="submenu">#}
{#                                          <li><a href="blog.html">blog</a></li>#}
{#                                          <li><a href="single-blog.html">single-blog</a></li>#}
{#                                      </ul>#}
{#                                  </li>#}
{#                                  <li><a href="#">pages <i class="ti-angle-down"></i></a>#}
{#                                      <ul class="submenu">#}
{#                                          <li><a href="elements.html">elements</a></li>#}
{#                                      </ul>#}
{#                                  </li>#}
                                  <li><a href="#speakers">Speakers</a></li>
                                  <li><a href="#organizers">Organizers</a></li>
                                  <li><a href="{% url 'certificates:home' %}">Certificates</a></li>
{#                                <li><a href="{% url 'mspsoc:project' %}">Projects</a></li>#}
{#                                  <li><a href="Venue.html">Venue</a></li>#}
{#                                  <li><a href="#contact">Contact</a></li>#}
                                  <li><a href="#faq">FAQs</a></li>
                              </ul>
                          </nav>
                      </div>
                  </div>
{#                  <div class="col-xl-2 col-lg-2 d-none d-lg-block">#}
{#                      <div class="buy_ticket">#}
{#                          <a href="#" class="boxed-btn-white">Buy Ticket</a>#}
{#                      </div>#}
{#                  </div>#}
                  <div class="col-12">
                      <div class="mobile_menu d-block d-lg-none"></div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</header>
<!-- header-end -->