config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("msp", include("microsoft_student_partners.msp.urls", namespace="msp")),
    path("", TemplateView.as_view(template_name="index.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("microsoft_student_partners.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        "certificates/",
        include(
            "microsoft_student_partners.certificates.urls", namespace="certificates"
        ),
    ),
    path(
        "mspsoc/",
        include("microsoft_student_partners.mspsoc.urls", namespace="mspsoc"),
    ),
    path(
        "qpower/",
        include("microsoft_student_partners.qpower.urls", namespace="qpower"),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

microsoft_student_partners/msp/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from microsoft_student_partners.msp.views import MspView

app_name = "msp"
urlpatterns = [
    path("", view=MspView.as_view(), name="home"),
    path(
        "services/",
        TemplateView.as_view(template_name="services.html"),
        name="services",
    ),
    path("about", TemplateView.as_view(template_name="about.html"), name="about",),
    path(
        "contact", TemplateView.as_view(template_name="contact.html"), name="contact",
    ),
]

microsoft_student_partners/msp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import View

class MspView(View):
    template_name = 'index.html'
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

microsoft_student_partners/msp/templates/about.html
{% extends 'mspbase.html' %}
{% load static %}
{% block content %}
         <div class="bg-banner-img clip-ellipse">
               <div class="ovrllay">

            {% include 'navbar.html' %}
            <!-- #banner start -->
            <section id="banner" class="pt-0">
               <div class="container ">
                  <div class="row">
                     <!-- #banner-text start -->
                     <div id="banner-text" class="col-md-12 text-c text-center ">
                        <h5 class="wow fadeInUp main-h" data-wow-delay="0.2s" >
                           About Us
                        </h5>
                        <p class="banner-text wow fadeInUp main-h3" data-wow-delay="0.8s">No hours sank into aggregating and cleaning data. No complex SQL queries required. Just the answers <br> teams need to make smarter decisions, fast. Now, that's data-driven.</p>
                     </div>
                     <!-- /#banner-text End -->
                  </div>
               </div>
            </section>
         </div>
      </div>
         <!-- /#banner end -->
         <!--#our_about_area -->
         <div class=" py-70 bg-about-img">
            <div class="container">
               <div class="row">
                  <div class="col-md-7 ">
                     <div class="title-lefts wow fadeInUp">
                        <h1>About us</h1>
                        <p class="bottom_h wow fadeInUp">We are the UK's leading supplier of road fuel and are growing internationally. </p>
                     </div>
                     <h2 class="about-s wow fadeInUp">This is our 27th year in business. </h2>
                     <p class="about-bottom-s wow fadeInUp">  We have grown from a bedroom start-up in 1992 to become<br> the UK's only national fuel supplier. We are now building on<br> our UK experience to grow internationally.</p>
                  </div>


                  <div class="col-md-5  back-shap">
                     <div class="all-text">
                        <h2 class="shap_top"> Our strategy </h2>
                        <p class="shap_bottom wow fadeInUp">By being the fuel supplier with the<br> lowest cost and the highest service<br> levels, we aim to earn the loyalty of<br> existing customers.
                        </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>

      <!--#End our_about_area-->
      <!-- #About Us Area start -->
      <div  id="about"  class=" back-right-text-c mt-50 wow fadeInUp ">
         <div class="container about_top-400">
            <div class="title wow fadeInUp mb_150  " style="visibility: visible; animation-name: fadeInUp;">
                  <h1 class="text-left pt-0">Lorem Ipsum <span class="font_30"> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been</span> </h1>

               </div>
            <div class="row">
               <div class="col-md-6  ">
               </div>
               <div class="col-md-6  ">

                  <div class="about-right wow fadeInUp">
                     <h1 class="text-left">Lorem Ipsum is simply dummy text printing    industry.</h1  >
                  </div>
               </div>
            </div>
            <div class="row text-left box-s">
               <div class="col-md-6">
                  <div class="title wow fadeInUp">
                     <img src="assets/images/image_about_left.jpg " class="posi-r-img">
                  </div>
                  <div class="">
                     <a href="#nogo" class="hero__play"> <img src="assets/images/img-2.png" class="video-a"></a>
                  </div>
               </div>
               <div class="col-md-6 wow fadeInUp">
                  <div class="services-right">
                     <p class="about_bottom_r">Lorem Ipsum is simply </p>
                     <p class="services-right-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,</p>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <div  id="about"  class=" back-right-text-c mt-50 ">
         <div class="container about_top-100">
           <div class="row">
               <div class="col-md-12  wow fadeInUp ">
                 <div class="about-right wow fadeInUp">
                     <h1 class="text-left">Lorem Ipsum is simply dummy text printing <br> industry.</h1  >
                  </div>
               </div>
            </div>
            <div class="row text-left box-s">
               <div class="col-md-6 wow fadeInUp">
                  <div class="services-right">
                     <p class="about_bottom_r">Lorem Ipsum is simply </p>
                     <p class="services-right-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,</p>
                  </div>
               </div>
               <div class="col-md-6">
                  <div class="title wow fadeInUp">
                     <img src="assets/images/image_about_right.jpg " class="posi-r-img">
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- End About Us Area -->
      <!-- #Our Team  Area start -->
      <section id="team" class="our_team_area">
         <div class="container">
            <div class="about-team wow fadeInUp" style="visibility: visible; animation-name: fadeInUp;">
               <h1 class="text-center">Our Team</h1>
            </div>
            <div class="row team_row">
               <div class="col-md-4 col-sm-6 wow fadeInUp" style="visibility: visible; animation-name: fadeInUp;">
                  <div class="team_membar">
                     <img src="assets/images/team/tm-1.jpg" alt="">
                     <div class="team_content">
                        <div class=" float-left  ">
                           <a href="#" class="name">Isabella Dowson</a>
                           <h6>Web Designer</h6>
                        </div>
                        <ul>
                           <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                           <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                           <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                        </ul>
                     </div>
                  </div>
               </div>
               <div class="col-md-4 col-sm-6 wow fadeInUp" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeInUp;">
                  <div class="team_membar">
                     <img src="assets/images/team/tm-2.jpg" alt="">
                     <div class="team_content">
                        <div class=" float-left  ">
                           <a href="#" class="name">Isabella Dowson</a>
                           <h6>Web Designer</h6>
                        </div>
                        <ul>
                           <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                           <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                           <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                        </ul>
                     </div>
                  </div>
               </div>
               <div class="col-md-4 col-sm-6 wow fadeInUp" data-wow-delay="0.3s" style="visibility: visible; animation-delay: 0.3s; animation-name: fadeInUp;">
                  <div class="team_membar">
                     <img src="assets/images/team/tm-3.jpg" alt="">
                     <div class="team_content">
                        <div class=" float-left  ">
                           <a href="#" class="name">Isabella Dowson</a>
                           <h6>Web Designer</h6>
                        </div>
                        <ul>
                           <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                           <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                           <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                        </ul>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
      <!-- End Our Team Us Area -->
      <!--#start Our testimonial Area -->
    <div class="our_partners_area bg-grediunt">
         <div class="book_now_aera ">
            <div class="container">
               <div class="row book_now">
                  <div class="col-md-5 booking_text">
                     <h4>Full insight into the customer journey.<br>
                        No SQL required.
                     </h4>
                     <p>Get started for free to see who your customers are, what they do and what keeps them coming back.</p>
                  </div>
                  <div class="col-md-7 p0 book_bottun">
                     <div class="col-md-7">

                     </div>
                     <div class="col-md-5">
                        <div class="top-banner wow fadeInRight text-left" style="visibility: visible; animation-name: fadeInRight;">
                           <a id="#services" href="contact.html" class="btn btn-primary  wow fadeInUp  js-scroll-trigger" data-wow-delay="1s" style="visibility: visible; animation-delay: 1s; animation-name: fadeInUp;">CONTACT SALES</a>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
         <!--#End Our testimonial Area -->
      {% include "footer.html" %}
      <!-- The following is only needed when the video is in the html
         otherwise the who .hero__overlay html can be removed -->
      <div class="hero__overlay">
         <div class="hero__modal">
            <a class="hero__close" href="#">Close</a>
            <iframe allowscriptaccess="always" id="hero-video" class="hero__player" src="https://www.youtube.com/embed/1NSA8ycGfKg?enablejsapi=1&html5=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
         </div>
         <!-- /.hero__modal -->
      </div>
 {% endblock content %}

microsoft_student_partners/msp/templates/contact.html
{% extends 'mspbase.html' %}
{% load static %}
{% block content %}
      <div class="bg-all">
      <div class="bg-banner-img clip-ellipse">
           <div class="ovrllay">

         {% include 'navbar.html' %}
         <!-- End Header_Area -->
         <!-- #banner start -->
         <section id="banner" class="pt-0">
            <div class="container ">
               <div class="row wow fadeInUp">
                  <!-- #banner-text start -->
                  <div id="banner-text" class="col-md-12 text-c text-center ">
                     <h5 class="wow fadeInUp main-h" data-wow-delay="0.2s" >Contact</h5>
                     <p class="banner-text wow fadeInUp main-h3" data-wow-delay="0.8s">No hours sank into aggregating and cleaning data. No complex SQL queries required. Just the answers <br> teams need to make smarter decisions, fast. Now, that's data-driven.</p>
                  </div>
                  <!-- /#banner-text End -->
               </div>
            </div>
         </section>
      </div>
    </div>
      <!-- /#banner end -->
      <!-- #contact  Area start -->
     <section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="section-heading left">
                    <h4>Let's Talk about Your Business</h4></div>
                <div class="contact-form-box margin-30px-top">
                    <div class="no-margin-lr" id="success-contact-form" style="display: none;"></div>
                    <form id="contactForm" method="post" class="contact-form" action="sendemail.php">
                        <div class="row">
                            <div class="col-md-12">
                                <input type="text" class="medium-input" maxlength="50" placeholder="Name *" required="required" id="name" name="name">
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <input type="email" class="medium-input" maxlength="70" placeholder="E-mail *" required="required" id="email" name="email">
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <input type="text" class="medium-input" maxlength="70" placeholder="Subject *" required="required" id="subject" name="subject">
                            </div>
                            <div class="col-md-12">
                                <textarea class="medium-textarea" rows="12" maxlength="1000" placeholder="Message *" required="required" id="message" name="message"></textarea>
                            </div>
                            <div class="col-md-12 sm-margin-30px-bottom">
                                <div class="top-contact wow fadeInRight text-left" style="visibility: visible; animation-name: fadeInRight;">
                           <a type="submit" id="#services" href="#services" class="btn btn-primary wow fadeInUp  js-scroll-trigger" data-wow-delay="1s" style="visibility: visible; animation-delay: 1s; animation-name: fadeInUp;">Send Message</a>
                        </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="contact-info-box padding-30px-left sm-no-padding">
                    <div class="row">
                        <div class="col-12">
                            <div class="contact-info-section no-padding-top margin-10px-top">
                                <h4>Get in Touch</h4>
                                <p> Tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse consequat.</p>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="contact-info-section">
                                <h4>The Office</h4>
                                <ul class="list-style-1 no-margin-bottom">
                                    <li>
                                        <p><i class="fa fa-phone text-center"></i> <strong>Address:</strong> Regina ST, London, SK 8GH.</p>
                                    </li>
                                    <li>
                                        <p><i class="fa fa-globe text-center"></i> <strong>Phone:</strong> (+44) 123 456 789</p>
                                    </li>
                                    <li>
                                        <p><i class="fa fa-envelope text-center"></i> <strong>Email:</strong> <a href="javascript:void(0)" class="email_color_site">email@youradress.com</a></p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="contact-info-section border-none no-padding-bottom no-margin-bottom">
                                <h4>Business Hours</h4>
                                <ul class="list-style-2">
                                    <li>Monday - Friday - 9am to 5pm</li>
                                    <li>Saturday - 9am to 2pm</li>
                                    <li>Sunday - Closed</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
   <!-- #contact  Area End -->



 <!--#Our maps  start -->
<section class="py_map_40">
   <div class="container-fluid p0">
      <div id="contatti" class=" maps">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11880.492291371422!2d12.4922309!3d41.8902102!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x28f1c82e908503c4!2sColosseo!5e0!3m2!1sit!2sit!4v1524815927977" frameborder="0" style="border:0" allowfullscreen=""></iframe>
                     </div>
   </div>
</section>

  <!--#End maps   -->


   <!--#Our Partners start -->
<div class="our_partners_area py-45">
            <div class="container">

               <!--#Our Partners assets/images start -->
               <div class="partners  pt-0 p0wow fadeInUp">
                  <div class="item"><img src="assets/images/client_logo/client_logo-1.png" alt=""></div>
                  <div class="item"><img src="assets/images/client_logo/client_logo-2.png" alt=""></div>
                  <div class="item"><img src="assets/images/client_logo/client_logo-3.png" alt=""></div>
                  <div class="item"><img src="assets/images/client_logo/client_logo-4.png" alt=""></div>
                  <div class="item"><img src="assets/images/client_logo/client_logo-5.png" alt=""></div>
               </div>
               <!--#End Our Partners assets/images -->

            </div>
         </div>
      <!--#End Our Partners Area -->


      <!--#End contact-text  -->
       <!--#start Our testimonial Area -->
    <div class="our_partners_area bg-grediunt">
         <div class="book_now_aera ">
            <div class="container">
               <div class="row book_now">
                  <div class="col-md-5 booking_text">
                     <h4>Full insight into the customer journey.<br>
                        No SQL required.
                     </h4>
                     <p>Get started for free to see who your customers are, what they do and what keeps them coming back.</p>
                  </div>
                  <div class="col-md-7 p0 book_bottun">
                     <div class="col-md-7">

                     </div>
                     <div class="col-md-5">
                        <div class="top-banner wow fadeInRight text-left" style="visibility: visible; animation-name: fadeInRight;">
                           <a id="#services" href="contact.html" class="btn btn-primary wow fadeInUp  js-scroll-trigger" data-wow-delay="1s" style="visibility: visible; animation-delay: 1s; animation-name: fadeInUp;">CONTACT SALES</a>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
         <!--#End Our testimonial Area -->
      {% include "footer.html" %}
{% endblock content %}

microsoft_student_partners/msp/templates/footer.html
{% load static %}
{% block footer %}
<!--#start Our footer Area -->
      <div class="our_footer_area">
         <div class="book_now_aera ">
            <div class="container wow fadeInUp">
               <div class="row book_now">
                  <div class="col-md-4">
                     <div class="">
                        <a class=" logo-biss" href="index.html"> <img src="{% static 'microsoft/Visual ID and Logo/Student Partner Visual ID/Blue_Black/CMYK/1Line/0419_MS_MSP_logo_Lockups_CMYK_MSP-1line-blue.jpg' %}"></a>
                     </div>
                     <p class="footer-h">MSPGlobal is the all-in-one live online events platform where attendees can learn, interact, and connect with MSPs from anywhere in the world.</p>
                     <div class="bigpixi-footer-social">
                        <a href="" target="_blank"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
                        <a href="" target="_blank"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
                        <a href="" target="_blank"><i id="social-em" class="fa fa-instagram fa-3x social"></i></a>
                     </div>
                  </div>
                  <div class="col-md-1 ">
                  </div>
                  <div class="col-md-3">
                     <h2 class="footer-top">Links </h2>
                     <ul class="footer-menu">
                        <li><a href="">Services</a></li>
                        <li><a href="">About</a> </li>
                        <li><a href="">Contact</a> </li>
                        <li><a href="">Events</a> </li>
                        <li><a href="">Webinars</a> </li>
                        <li><a href="">Developers</a></li>
                     </ul>
                  </div>
                  <div class="col-md-4">
                     <ul class="location">
                        <li class="footer-left-h"><i class="fa fa-map-marker"></i>505 Thornall St #301, Edison, <br>NJ 08837, USA</li>
                        <li class="footer-left-h"><i class="fa fa-phone"></i>Call Us <br>+1- 982-8-587 452
                           <br>+1- 982-8-587 452
                        </li>
                        <li class="footer-left-h"><i class="fa fa-envelope-o"></i>Email<br>
                           <a href=""> enquiry@demo.com </a></br><a href=""> enquiry@demo.com </a>
                        </li>
                        <p class="color-gray">
                           <a href="https://themewagon.com/theme_tag/free/">Free HTML5 Templates</a> distributed by <a href="https://themewagon.com/">ThemeWagon</a>
                        </p>
                     </ul>
                  </div>
                   <div class="col-md-12">
                    <p class="color-gray">  <a href="https://www.navthemes.com/free-html-templates/">Free HTML Template</a> by <a href="https://www.navthemes.com">NavThemes </a> </p>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!--#End Our footer Area -->
{% endblock footer %}

microsoft_student_partners/msp/templates/mspbase.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>msp</title>
      <!-- Favicon -->

      <!-- Bootstrap CSS -->
      <link href="{% static 'css/bootstrap.min.css' %}{% now '?U' %}" rel="stylesheet">
      <!-- Animate CSS -->
      <link href="{% static 'vendors/animate/animate.css' %}{% now '?U' %}" rel="stylesheet">
      <!-- Icon CSS-->
      <link rel="stylesheet" href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}{% now '?U' %}">
      <!-- Owlcarousel CSS-->
      <link rel="stylesheet" type="text/css" href="{% static 'vendors/owl_carousel/owl.carousel.css' %}{% now '?U' %}" media="all">
      <!--Template Styles CSS-->
      <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}{% now '?U' %}" media="all" />
      <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese" rel="stylesheet">
   </head>
   <body>
      {% block content %}
      {% endblock content %}

      {% block javascript %}
      <!-- jQuery JS -->
      <script src="{% static 'js/jquery-1.12.0.min.js' %}{% now '?U' %}"></script>
      <!-- Bootstrap JS -->
      <script src="{% static 'js/bootstrap.min.js' %}{% now '?U' %}"></script>
       <script src="{% static 'vendors/popup/lightbox.min.js' %}{% now '?U' %}"></script>
      <!-- Animate JS -->
      <script src="{% static 'vendors/animate/wow.min.js' %}{% now '?U' %}"></script>
      <!-- Owlcarousel JS -->
      <script src="{% static 'vendors/owl_carousel/owl.carousel.min.js' %}{% now '?U' %}"></script>
      <!-- Stellar JS -->

      <!-- Theme JS -->
      <script src="{% static 'js/theme.min.js' %}{% now '?U' %}"></script>
      {% endblock javascript %}
   </body>
</html>

microsoft_student_partners/msp/templates/navbar.html
{% load static %}
<!-- Header_Area -->
<nav class="navbar navbar-default header_aera affix-top">
<div class="container m-s">
   <!-- Brand and toggle get grouped for better mobile display -->
   <div class="col-md-4 p0">
      <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#min_navbar">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         </button>
{#         <a class="navbar-brand logo-biss" href="index.html"> <img src="{% static 'images/logo_img.png' %}"></a>#}
      </div>
   </div>
   <!-- Collect the nav links, forms, and other content for toggling -->
   <div class="col-md-8 p0">
      <div class="collapse navbar-collapse" id="min_navbar">
        <ul class="nav navbar-nav navbar-right">
      <li class="dropdown submenu">
         <a href="{% url 'msp:home' %}" class="">Home</a>
      </li>
      <li class="dropdown submenu">
         <a href="{% url 'msp:services' %}" class=""> Services</a>
      </li>
      <li class="dropdown submenu">
         <a href="{% url 'msp:about' %}" class="">About</a>
      </li>
{#      <li class="dropdown submenu">#}
{#         <a href="blog.html" class="">Blog</a>#}
{#      </li>#}
{#      <li class="dropdown submenu">#}
{#         <a href="elements.html" class="">Elements</a>#}
{#      </li>#}
      <li class="dropdown submenu">
         <a href="{% url 'msp:contact' %}" class="">Contact</a>
      </li>

   </ul>
      </div>
      <!-- /.navbar-collapse -->
   </div>
</div>
<!-- /.container -->
</nav>
<!-- End Header_Area -->